### ISSUE TITLE
Subject toolbar doesn't resize with subject image

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/wildcam-gorongosa#143]
At certain widths the buttons aren't even visible:

https://dl.dropboxusercontent.com/u/246492/wildcam-resize.mov

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9

**Comment by srallen** [comment]
This probably got messed up when I fixed #139

**Comment by aliburchard** [comment]
I'm going to work with @astopy to just resize the images and host ourselves, since hhmi can't seem to get their data management company to size to a consistent width. (they can only resize to 500 px tall, apparently.) 

Once we resize for them, if we revert the changes from 139, would that fix this?

**Comment by aliburchard** [comment]
In playing with this a bit more, I think we need to undo the changes made to fix  #139 - sorry @srallen  :-/ -- I can't see the buttons at all on most screen sizes.

**Comment by chrissnyder** [comment]
Do we really need to resize all the images? Surely some careful CSS would solve this problem. Unless I'm entirely misunderstanding the issue.

**Comment by srallen** [comment]
Yeah, it doesn't need to be reverted. Just the style being added to the subject-toolbar should be `maxWidth: @state.subject?.srcWidth` rather than width and the max-width removed from the `subject-toolbar` class. That was my bad not catching that it was messing up the responsiveness for the classifier.

**Comment by aliburchard** [comment]
Is that an easy fix? I'm acutely aware of the fact that you guys have other things to work on; at the same time, I think this is important to solve before the public launch. So I wanted to come up with a solution that avoided pinging you as much as possible.

**Comment by srallen** [comment]
Yeah, I just opened #150 that fixed it for me. Let me know if it's fixed for you.

**Comment by srallen** [comment]
Ok, #150 is merged and deployed to production.

**Comment by aliburchard** [comment]
thanks!!
