### ISSUE TITLE
Unable to sing-in with separate account

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/wildcam-gorongosa#184]
If I log out and then click sign-in, it signs me back in with the same account instead of giving me the option to choose. 

I was logged in to PFE with a separate account, but it didn't allow me to sign into WildCam with that account. Just signed me in with the last  account I had signed in with.

**Comment by camallen** [comment]
I was debugging this with grant. Turns out if you have a panoptes session already in play then it uses this to sign you in. Since [here](https://github.com/zooniverse/wildcam-gorongosa/blob/master/app/api/config.coffee#L4) uses panoptes to sign in it will leave a session. Probably best to change that like the [front end did](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/api/config.coffee#L4) to use zooniverse.org and ensure that signout removes the cookies for the relevant domains.
