### ISSUE TITLE
Style "clear filters" area on classifier

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/wildcam-gorongosa#22]

**Comment by srallen** [comment]
@heathv, currently the survey task filters are using the no symbol for the 'other' option. In your design it looks like the no symbol is for clearing the filters, which makes sense. How should the 'other' button option be styled so that the no symbol can be used for clearing the filters?

**Comment by aliburchard** [comment]
It actually sounds like there are two things in this issue: 
1) the "clear all filters" is currently invisible because it's black text on dark background.
2) the "other" filter in the "like" category, which uses the same icon as does "clear", and that's confusing
3) plus HHMI has also requested that we use the text "clear" instead of the circle witha line through it.

...I can count, really.

I'd be fine replacing the "other" and "clear" with text instead of symbols (or text and symbols). for the "clear all" bit, if we at the very least make it white text, it will appear.
