### ISSUE TITLE
sign in pop-up is scary

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#94]
Following #77, you can now sign in, but the screen is super ominous -- can we change that? Not sure if this is an @edpaget thing or someone else.

![screen shot 2015-08-27 at 10 15 23](https://cloud.githubusercontent.com/assets/6217406/9517163/c896cfca-4ca5-11e5-8b4e-7b571f61c2ae.png)

**Comment by ggdhines-zz** [comment]
Also missing a word or two after "This application will be able to"

**Comment by edpaget** [comment]
Yes this will be removed for applications we run.

**Comment by aliburchard** [comment]
aha! @edpaget what does that actually mean/how does that work? 

will that automatically go away when we push the project to production or do we need to do something to make that happen?

We're doing a soft launch on Sept 1 to HHMI partners and teachers and such, and don't want to make them panic.

**Comment by edpaget** [comment]
You're welcome to open another issue on Panoptes about making the warning less scary since that's the page anyone who writes an application on top of Panoptes (who is not us) will see, but it's not really any different than what'd you see using a 'Login with Facebook' or 'Login with Twitter' button. 

I'll look into fixing it while I'm on the plane.

**Comment by edpaget** [comment]
For a real explanation every application that interacts with Panoptes has a unique application id / secret key pair that they use to ensure that we can track who is using our API and for what. When a user logs in they're actually giving the application permission to send requests to our API on their behalf. User have to permit applications to access different 'scopes' of resource, so ideally applications request the least number of permissions they need to work (which is what's happening on the page you're seeing there).

In our database we've marked which applications are ones we control and I'll simply skip this page when you login for those applications, since it's silly to have users approve application permissions when we already control all that data anyway.

**Comment by aliburchard** [comment]
Aha! Thanks for the explanation. That's actually really cool to know (and not really stuff I'd thought about before).

I do think it makes sense to skip that screen for apps that we build/control. Thanks!

**Comment by aliburchard** [comment]
yay! thanks ed!
